src/streamstats/bootstrap.jl
test/testfiles/streamstats_test.jl

I made two Poisson bootstrap object types so as to keep the cached_state attribute typed. If for performance that does not actually matter then we could merge them.

Added support for VectorInput Poisson bootstraps.

---

src/streamstats/bootstrap.jl

Avoids copying the replicates and creating new distribution objects every time. Results in 7-11x faster execution on my Mac Air on v0.4.5 when using Mean() or Means() as the replicated statistic.

Make Poisson bootstraps much faster.

---

src/distributions.jl
test/testfiles/distributions_test.jl
test/testfiles/multivariate_test.jl

One of the constructors was missing a () for EqualWeight, fixed that.
Added tests for MvNormal.

MvNormal: fix missing (), add tests.

---

src/distributions.jl
src/multivariate/kmeans.jl
src/streamstats/bootstrap.jl
src/streamstats/hyperloglog.jl
src/summary.jl

Hello. to follow the changes on Julia 0.6,
- fix the invalid subtyping error by `HyperLogLog`
- update deprecated functions `sqrt.`, `sum(abs2, itr)`, `Array{T}(m)`
thanks.

Fix the invalid subtyping error for HyperLogLog, update sqrt, sumabs2, Array(T, m)

---

src/vectorinput/mv.jl

Fixes #85 
Now looks:
```
julia> Series(OnlineStats.EqualWeight(), MV(n, Mean()), MV(n, Variance()), MV(n, Extrema()), MV(n, QuantileSGD([0.1,0.25,0.5,0.75,0.9])) )            
▦ Series{1,Tuple{MV{Mean},MV{Variance},MV{Extrema},MV{QuantileSGD}},EqualWeight}                                                                      
┣━━ EqualWeight(nobs = 0)                                                                                                                             
┗━━ Tracking                                                                                                                                          
┣━━ MV{Mean}(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...)                                                                               
┣━━ MV{Variance}(-0.0, …
```

Fix printing of big MVs

---

src/stats/histograms.jl
src/visualizations/recipes.jl
test/test_stats.jl

Hi,
while playing around with OnlineStats, I noticed that I would like to create histograms with non-uniform bins of fixed width and hence be able to specify general `AbstractVector`s as edge vectors of fixed-width bins. I'm not sure whether it is of general interest, but this PR resolves that issue by slightly changing the current implementation. Moreover, similar to the code in StatsBase.jl, I added an option for switching between left-closed and right-closed bins (only for histograms with fixed-width bins).

Histograms with general fixed-width bins

---

src/stats/stats.jl
src/utils.jl
test/runtests.jl

Changes to type parameterization and methods, includes tests.
My editor also automatically deleted a bunch of trailing whitespaces...the number of changed lines is not actually that many.
The way I did it, `CovMatrix()` still defaults to `Float64`, and if the user tries to fit it to data of some other type it [throws an error,](https://github.com/ElOceanografo/OnlineStats.jl/blob/ca958ed81f1dfd22e12360c62a7db819e54ded38/src/stats/stats.jl#L285) suggesting they construct the `CovMatrix` explicitly with the type they need.  Alternatively there could be automatic promotion...not sure what you think would be better?

Allow CovMatrix to fit any data of type Number, not just Float64

---

src/OnlineStats.jl
src/stats/kahan.jl
test/runtests.jl
test/test_kahan.jl

Interested? There is a problem: in all my tests this was identical to `Sum()` for both `Float32` and `Float64`, I have the suspicion, that the compiler simply optimizes the correction away. Any idea how to prevent this? I already tried `julia --math-mode=ieee -O0`:
```julia
julia> d = (rand(1_000_000) .^ 3) |> sort |> reverse;
julia> d32 = Float32.(d);
julia> 
julia> sum(d) - sum(d32)
-0.012182071630377322
julia> reduce(+, d) - reduce(+, d32)
-0.012182071630377322
julia> foldr(+, d) - foldr(+, d32)
-7.543432063568616
julia> foldl(+, d) - foldl(+, d32)
217.95656791204237
julia> s64 = Sum(Float64); s32 = Sum(Float32);
julia> sum(fit!(s64, d)) - sum(fit!(s32, d))
217.95656791204237
julia> ks64 = KahanSum(Float64); ks32 = KahanSum(Float32);
julia> sum(fit!(ks64, d)) - sum(fit!(ks32, d)) …
```

add kahan summation, mean, and variance

---

src/viz/partition.jl

Fixes plotting of `IndexedPartition` with `Date` or `DateTime` index.
```julia
using Dates
x = Date(2010):Day(1):Date(2011)
y = rand(1:10, length(x))
o = fit!(IndexedPartition(Date, CountMap(Int)), zip(x, y))
plot(o)
```

Add midpoint method for TimeType

---

src/stats/distributions.jl
src/stats/fasttree.jl
src/stats/linreg.jl
src/stats/nbclassifier.jl
src/stats/statlearn.jl
src/stats/stats.jl

vim insisted on adding a newline at the end of every file.

Fixed docs examples to explicitly iterate over observation rows

---

src/OnlineStats.jl
src/stats/pca.jl
test/runtests.jl
test/test_ccipca.jl

This implements the CCIPCA (Candid Covariance-free Incremental PCA) algorithm which is a fast, approximate PCA. Also has quite extensive tests including differential testing with the CCIPCA implementation of the R package onlinePCA. I also propose to export the transform method from OnlineStats but I have NOT done so in this PR.

CCIPCA algorithm for online PCA

---

README.md

ThreadsX.jl provides [an easy-to-use interface for threaded reduction with OnlineStats.jl](https://github.com/tkf/ThreadsX.jl#onlinestatsjl) on top of Transducers.jl.  I wonder if it is appropriate to mention it in the README.
I also fixed the link to Transducers.jl.

Link ThreadsX.jl

---

src/stats/stats.jl

The MovingTimeWindow is currently
```julia
MovingTimeWindow{T<:TimeType, S, D<:DatePeriod} <: OnlineStat{TwoThings{T,S}}
```
This commit changes DatePeriod to Period
```julia
MovingTimeWindow{T<:TimeType, S, D<:Period} <: OnlineStat{TwoThings{T,S}}
```
See
https://en.wikibooks.org/wiki/Introducing_Julia/Working_with_dates_and_times

Use Period in MovingTimeWindow

---

src/stats/stats.jl

This pull request solves a little mistake in the `_fit!` method for `HyperLogLog`.
The algorithm uses a 32 bit hash code, with `p` bits reserved to indicate the register to update. The other `q` (`= 32 - p`) bits are used to determine the number of leading zeros. The problem in the current implementation is that if all bits are zero then the result of `leading_zeros(w)` will be `32` instead of the desired value `q`, because the object `w` is a `UInt32` with the last `p` bits set to zero.
By construction this problem happens for very large cardinalities, close to the limit 2^32 where the HyperLogLog algorithm is in any case hitting its limitations. So the bias introduced by this mistake is in practice very small.
This was found in the context of …

fix HyperLogLog leading zeros

---

src/stats/stats.jl

This pull request implements the improved HyperLogLog  estimator as suggested in https://github.com/joshday/OnlineStats.jl/issues/177.
The existing `fit!` and `merge!` methods for the HyperLogLog  OnlineStat remain the same, and only the HyperLogLog estimator (i.e. `value` method)  changes. The improved estimator is returned by default, but the original estimator can be obtained using the `original_estimator=true` option.
The chosen implementation for sigma and tau does not follow exactly the implementation suggested by @StefanKarpinski in #177. It rather follows *Algorithm 6* as described in detail in https://arxiv.org/pdf/1702.01284.pdf, which is pretty efficient as discussed in the paper. In particular sigma and tau are not precalculated for all possible values of C_k. The reason for …

improved HyperLogLog estimator

---

src/stats/stats.jl

I noticed the reservoir sampling was never reassigning the `k`th element, this is just a single letter fix.
Up: before MR
Below: after

Fix inequality in reservoir sampling

---

docs/src/stats_and_models.md

Hello!  I'm only now realizing quite how awesome this package is.  Even though there is a ton of (great!) documentation, a few things are a bit buried and I almost didn't realize they existed.
Especially `StatLearn`, that seems like kind of a big deal.
This adds `StatLearn` and its possible arguments to a dedicated new section of the "Stats and Models" section of the docs.  I tried to make this consistent with the existing format, but please feel free to suggest changes.

tried to make StatLearn more discoverable in docs

---

src/stats/stats.jl

Currently `ReservoirSample` only accept `Number` types and implements a constructor based on `zeros`.
This PR changes `ReservoirSample` so it can accept any generic type `T`, and implements a constructor for `AbstractString` types using empty strings. Other types that implement the method `zero` (e.g. `TimeTypes`) will work.

ReservoirSample with generic type

---

Project.toml
src/stats/distributions.jl
test/runtests.jl

Hey, 
working with MvNormal, I noticed that the `mean`, `var`, and `cov` function were not defined for `FitMvNormal`, even though they exist for `FitNormal`. This MR adds them. 
Further, I noticed that in the edge cases that the same (exact) same value is added a few times, the fallback mean and variance were returned. With this MR the behaviour becomes: 
```julia
julia> m = FitMvNormal(2)
FitMvNormal: n=0 | value=([0.0, 0.0], [-0.0 -0.0; -0.0 -0.0])
julia> a = rand(2)
2-element Vector{Float64}:
0.5760181131344163
0.5890715541785612
julia> for i in 1:5
fit!(m, a)
end
julia> m
FitMvNormal: n=5 | value=([0.576018, 0.589072], [0.0 0.0; 0.0 0.0])
```

Small fixes for `FitMvNormal`

---

Project.toml
src/stats/stats.jl
test/runtests.jl

Fixes https://github.com/joshday/OnlineStats.jl/issues/269
I tried to make the test a bit less copy-pasta with 
```julia
for property in (:cross, :m1, :m2, :lag, :wlag, :v)
@eval begin
@test (@inferred ((o) -> o.property)(o)) === o.property
end
end
```
but unfortunately, that doesn't work since `@eval` always works in global scope, so I just copy-pasted it.
You can test that this solves the issue with `_fit!` by running:
```julia
@code_warntype OnlineStats._fit!(AutoCov(10), randn(100))
```
Suggestions, comments, and feedback are welcome!

fix type stability in autocov and add a unit test

---

src/stats/stats.jl
test/runtests.jl

OrderStats is currently implemented using an internal `Extrema` statistic. Would it make sense to expose that?
Specifically, we could implement:
* `Base.minimum`
* `Base.maximum`
* `Base.extrema`
* Conversion to `Extrema`, which creates a copy of the internal `Extrema`

Expose extrema of OrderStats
